#!/bin/bash
#
# Usage: publish_versions.sh path pubdir [regex]
# Create version copies of 'path' in directory 'pubdir'.
#
# For each tag (matching 'regex' if 'regex' is given), get a version of
# 'path' corresponding to that tag.  Then copy it to 'pubdir' and renamed
# to the tag name.
#
# 'path' may be a file or a directory and should be specified relative
# to the git root dir.
#
# 'pubdir' must be an existing directory.  It should be specified relative
# to the git root dir.
#
# If 'regex' is given, it should be a regular expression.  Only tag names
# matching 'regex' will be considered.
#
[ $# -lt 2 -o $# -gt 3 ] && \
    echo "Usage: publish_versions path pubdir [regex]" >&2 && \
    exit 1
path="$1"
pubdir="$2"
regex="$3"

# Enter git root directory
rootdir="$(git rev-parse --show-toplevel)"  # git root dir
cd "$rootdir"

set -x

for tag in $(git tag); do
    # If 'regex' is provided, only publish tags matching 'regex'
    if [ -n "$regex" ] && [[ ! $tag =~ $regex ]]; then
        continue
    fi

    if [ ! -e $pubdir/$tag ]; then
        if [ $tag == $(git describe --tag) ]; then
            cp -rp $path $pubdir/$tag
        else
            echo "Missing documentation for tag: $tag" >&2
        fi
    fi
done
