#!/usr/bin/env python3
"""Tool for checking that ontologies conform to EMMO conventions.
"""
import sys
import os

# Support to run from uninstalled version by adding parent dir to sys path
rootdir = os.path.abspath(os.path.realpath((os.path.dirname(
    os.path.dirname(__file__)))))
sys.path.insert(1, rootdir)

from emmopy.emmocheck import main  # noqa: E402


if __name__ == '__main__':
    sys.exit(main())
