#!/usr/bin/env python3
"""Creates and ontology from an excelfile.

The excel file must be in the formate provided by
ontology_template.xlsx
"""
import argparse
import sys
import pyparsing
import pandas as pd
from ontopy import World
from ontopy.utils import NoSuchLabelError
from ontopy.manchester import evaluate
from ontopy.excelparser import create_ontology_from_excel
import owlready2  # pylint: disable=C0411


def english(string):
    """Returns `string` as an English location string."""
    return owlready2.locstr(string, lang="en")


def main():
    """Main run function."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "excelpath",
        help="path to excel book",
    )
    parser.add_argument(
        "--name",
        "-n",
        default="ontology.ttl",
        help="Name of ontology, ´ontology.ttl´ is default",
    )
    try:
        args = parser.parse_args()
    except SystemExit as exc:
        sys.exit(exc.code)  # Exit without traceback on invalid arguments


    onto = create_ontology_from_excel(args.excelpath) 

    # Save new ontology as turtle
    onto.save(
            os.path.join(arg.name), format="turtle", overwrite=True
    )

if __name__ == "__main__":
    main()
